[config]
exclude-merge-commits = true
check-summary-length  = true
summary-length        = 80

[matchers]
all = "(?:build|ci|deps|docs|feat|fix|lint|perf|refactor|relprep|style|test)(?:\\([^\\)]*\\))?: (?:.+)"

[examples]
a_simple_commit = """
[build|ci|deps|docs|feat|fix|lint|perf|refactor|relprep|style|test](module): A commit message
"""
an_extended_commit = """
[build|ci|deps|docs|feat|fix|lint|perf|refactor|relprep|style|test](module): A commit message

* first line
* second line
* and so on...
"""
