---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.12

default_stages:
  - pre-commit
  - pre-push

fail_fast: false

repos:
  # ----------------------------------------------------------------------------
  # goplicate-start:always
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=500
          - --enforce-all
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: destroyed-symlinks
      # - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace

  # ----------------------------------------------------------------------------
  # goplicate-start:golang
  - repo: https://github.com/skyzyx/git-hooks
    rev: 4a2f0dc93e5c5353ed5e619599b0d15e34df88db
    hooks:
      - id: gofumpt
      - id: golangci-lint

  - repo: local
    hooks:
      - id: unconvert
        name: "Go: unconvert (current GOOS/GOARCH)"
        description: Analyzes Go packages to identify unnecessary type conversions.
        entry: bash -c 'go tool -modfile=go.tools.mod unconvert -fastmath -tests -v ./...'
        language: system
        stages: [pre-commit, pre-push]

      - id: smrcptr
        name: "Go: Same Receiver Pointer"
        description: Don't mix receiver types. Choose either pointers or struct types for all available methods.
        entry: bash -c 'go tool -modfile=go.tools.mod smrcptr --constructor=true ./...'
        language: system
        stages: [pre-commit, pre-push]

      - id: govulncheck
        name: "Go: Vulnerability check"
        description: Check for Go security vulnerabilities. (https://go.dev/blog/vuln)
        entry: bash -c 'go tool -modfile=go.tools.mod govulncheck -test ./...'
        language: system
        stages: [pre-commit, pre-push]

      - id: osvscanner
        name: OSV Scanner
        description: Check for security vulnerabilities. (https://osv.dev)
        entry: bash -c 'go tool -modfile=go.tools.mod osv-scanner -r .'
        language: system
        stages: [pre-commit, pre-push]
  # goplicate-end:golang

  # ----------------------------------------------------------------------------
  # goplicate-start:terraform
  - repo: https://github.com/skyzyx/git-hooks
    rev: 4a2f0dc93e5c5353ed5e619599b0d15e34df88db
    hooks:
      - id: terraform-fmt
  # goplicate-end:terraform

  # Project-specific tasks
  - repo: local
    hooks:
      - id: go-consistent
        name: "Go: Consistent Patterns"
        description: Analyzes Go packages to identify unnecessary type conversions.
        entry: |-
          bash -c 'go tool -modfile=go.tools.mod go-consistent ./corefunc/...; \
            go tool -modfile=go.tools.mod go-consistent ./corefuncprovider/...'
        language: system
        stages: [pre-commit, pre-push]
