##
# Generate with:
#   tomljson ecrc.toml > .editorconfig-checker.json
##

# @config-manager:start config
Debug           = false
IgnoreDefaults  = true
NoColor         = false
SpacesAfterTabs = false
Verbose         = false
# @config-manager:end config

Exclude = [
  # @config-manager:start excludes
  # Directories
  "\\.config-manager\\.d/",
  "\\.github/workflows/",
  "\\.kiro/",
  "\\.kirograph/",
  "\\.rumdl_cache/",
  "\\.venv",
  "\\.vite/",
  "node_modules/",
  "testdata/",
  "testfixtures/.*$",

  # Files
  "Cargo\\.lock$",
  "LICENSE(\\.(md|txt))?$",
  "Taskfile\\.([^\\.]+)\\.(yaml|yml)$",
  "Taskfile\\.(yaml|yml)$",
  "TerraformOptions.json$",
  "\\.7z$",
  "\\.avif$",
  "\\.bak$",
  "\\.bin$",
  "\\.bz2$",
  "\\.cache$",
  "\\.css\\.map$",
  "\\.dcignore$",
  "\\.ecrc$",
  "\\.editorconfig-checker\\.json$",
  "\\.eot$",
  "\\.example$",
  "\\.gif$",
  "\\.git/.*$",
  "\\.go$",
  "\\.golangci\\.yml$",
  "\\.goreleaser\\.yml$",
  "\\.gotmpl$",
  "\\.gz$",
  "\\.ico$",
  "\\.infracost/.*$",
  "\\.jpeg$",
  "\\.jpg$",
  "\\.js\\.map$",
  "\\.jsonschema\\.json$",
  "\\.lefthook-local/.*$",
  "\\.lefthook/.*$",
  "\\.licenses\\.cache\\.json$",
  "\\.lock$",
  "\\.log$",
  "\\.mp4$",
  "\\.otf$",
  "\\.out$",
  "\\.patch$",
  "\\.pbm$",
  "\\.pdf$",
  "\\.pgm$",
  "\\.png$",
  "\\.pnm$",
  "\\.ppm$",
  "\\.snap$",
  "\\.svg$",
  "\\.tar$",
  "\\.terraform-docs\\.yml$",
  "\\.terraform/.*$",
  "\\.terraform\\.lock\\.hcl$",
  "\\.tfstate$",
  "\\.tfstate\\.backup$",
  "\\.ttf$",
  "\\.txt$",
  "\\.vscode/.*?\\.(json|sh|toml|yaml|yml)$",
  "\\.webp$",
  "\\.wmv$",
  "\\.woff$",
  "\\.woff2$",
  "\\.zip$",
  "^\\.pnp\\.cjs$",
  "^\\.pnp\\.js$",
  "^\\.pnp\\.loader\\.mjs$",
  "^\\.yarn/",
  "^package-lock\\.json$",
  "aube-lock\\.yaml$",
  "cliff\\.toml$",
  "composer\\.lock$",
  "go\\.mod$",
  "go\\.sum$",
  "go\\.tools\\.mod$",
  "go\\.tools\\.sum$",
  "manifest\\.json$",
  "min\\.css$",
  "min\\.js$",
  "package-lock\\.json$",
  "package\\.json$",
  "pnpm-lock\\.yaml$",
  "pnpm-workspace\\.yaml$",
  "poetry\\.lock$",
  "standard\\.mk$",
  "yarn\\.lock$",
  # @config-manager:end excludes
]
