#!/usr/bin/env bats
# https://bats-core.readthedocs.io/en/stable/writing-tests.html

@test "listing the data sources" {
    run tfschema data list corefunc

    [[ ${status} -eq 0 ]]
    [[ ${lines[0]} == "corefunc_env_ensure" ]]
    [[ ${lines[1]} == "corefunc_hash_argon2id" ]]
    [[ ${lines[2]} == "corefunc_hash_argon2id_base64" ]]
    [[ ${lines[3]} == "corefunc_hash_bcrypt" ]]
    [[ ${lines[4]} == "corefunc_hash_hmac_base64sha256" ]]
    [[ ${lines[5]} == "corefunc_hash_hmac_sha256" ]]
    [[ ${lines[6]} == "corefunc_hash_md5" ]]
    [[ ${lines[7]} == "corefunc_hash_md5_base64" ]]
    [[ ${lines[8]} == "corefunc_hash_scrypt" ]]
    [[ ${lines[9]} == "corefunc_hash_scrypt_base64" ]]
    [[ ${lines[10]} == "corefunc_hash_sha1" ]]
    [[ ${lines[11]} == "corefunc_hash_sha1_base64" ]]
    [[ ${lines[12]} == "corefunc_hash_sha256" ]]
    [[ ${lines[13]} == "corefunc_hash_sha256_base64" ]]
    [[ ${lines[14]} == "corefunc_hash_sha384" ]]
    [[ ${lines[15]} == "corefunc_hash_sha384_base64" ]]
    [[ ${lines[16]} == "corefunc_hash_sha3x256" ]]
    [[ ${lines[17]} == "corefunc_hash_sha3x256_base64" ]]
    [[ ${lines[18]} == "corefunc_hash_sha3x384" ]]
    [[ ${lines[19]} == "corefunc_hash_sha3x384_base64" ]]
    [[ ${lines[20]} == "corefunc_hash_sha3x512" ]]
    [[ ${lines[21]} == "corefunc_hash_sha3x512_base64" ]]
    [[ ${lines[22]} == "corefunc_hash_sha512" ]]
    [[ ${lines[23]} == "corefunc_hash_sha512_base64" ]]
    [[ ${lines[24]} == "corefunc_homedir_expand" ]]
    [[ ${lines[25]} == "corefunc_homedir_get" ]]
    [[ ${lines[26]} == "corefunc_int_leftpad" ]]
    [[ ${lines[27]} == "corefunc_json_to_toml" ]]
    [[ ${lines[28]} == "corefunc_net_cidr_contains" ]]
    [[ ${lines[29]} == "corefunc_runtime_cpuarch" ]]
    [[ ${lines[30]} == "corefunc_runtime_numcpus" ]]
    [[ ${lines[31]} == "corefunc_runtime_os" ]]
    [[ ${lines[32]} == "corefunc_str_base64_gunzip" ]]
    [[ ${lines[33]} == "corefunc_str_camel" ]]
    [[ ${lines[34]} == "corefunc_str_constant" ]]
    [[ ${lines[35]} == "corefunc_str_contains" ]]
    [[ ${lines[36]} == "corefunc_str_endswith" ]]
    [[ ${lines[37]} == "corefunc_str_iterative_replace" ]]
    [[ ${lines[38]} == "corefunc_str_kebab" ]]
    [[ ${lines[39]} == "corefunc_str_leftpad" ]]
    [[ ${lines[40]} == "corefunc_str_pascal" ]]
    [[ ${lines[41]} == "corefunc_str_snake" ]]
    [[ ${lines[42]} == "corefunc_str_startswith" ]]
    [[ ${lines[43]} == "corefunc_time_parse" ]]
    [[ ${lines[44]} == "corefunc_toml_to_json" ]]
    [[ ${lines[45]} == "corefunc_url_decode" ]]
    [[ ${lines[46]} == "corefunc_url_parse" ]]
}
