---
blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/northwood-labs/terraform-provider-corefunc/discussions
    about: Please ask and answer questions here.
