---
name: Feature Request
description: Request new functionality.
title: '[Feature]: '
labels: [feature, triage]
assignees:
  - skyzyx
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: what-do-you-want
    attributes:
      label: What functionality would you like to see?
      description: This should be functionality that (a) is not built into Terraform, (b) can be implemented via a Terraform
        provider, and (c) can be implemented as a function in Go.
      placeholder: ''
      value: ''
    validations:
      required: true
