# https://google.github.io/osv-scanner/configuration/

[[IgnoredVulns]]
  id = "GO-2022-0646"
  reason = "Not leveraging this functionality in our codebase"
  # ignoreUntil = YYYY-MM-DD

[[IgnoredVulns]]
  id = "GO-2025-3829"
  reason = "Not leveraging this functionality in our codebase"
  # ignoreUntil = YYYY-MM-DD
