recommendations = [
  # @config-manager:start standard
  '1password.op-vscode',
  'albymor.increment-selection',
  'anchoreinc.grype-vscode',
  'annsk.alignment',
  'aquasecurityofficial.trivy-vulnerability-scanner',
  'arr.marksman',
  'bierner.markdown-checkbox',
  'bierner.markdown-preview-github-styles',
  'chdsbd.github-code-owners',
  'christian-kohler.path-intellisense',
  'claui.email-addresses',
  'cmacu.gotoanything',
  'codezombiech.gitignore',
  'darkriszty.markdown-table-prettify',
  'davidwang.ini-for-vscode',
  'dreden33773.vhs-analyzer',
  'eamodio.gitlens',
  'editorconfig.editorconfig',
  'emeraldwalk.runonsave',
  'esbenp.prettier-vscode',
  'flesler.url-encode',
  'formulahendry.auto-close-tag',
  'formulahendry.auto-rename-tag',
  'foxundermoon.shell-format',
  'geeebe.duplicate',
  'gurumukhi.selected-lines-count',
  'hbenl.vscode-test-explorer',
  'jq-syntax-highlighting.jq-syntax-highlighting',
  'kevinkyang.auto-comment-blocks',
  'mads-hartmann.bash-ide-vscode',
  'melt-inc.yamlfmt-vscode',
  'mkxml.vscode-filesize',
  'ms-vscode.makefile-tools',
  'ms-vscode.test-adapter-converter',
  'nhoizey.gremlins',
  'oliversturm.fix-json',
  'pflannery.vscode-versionlens',
  'pkl.pkl-vscode',
  'quicktype.quicktype',
  'redhat.vscode-yaml',
  'rogalmic.bash-debug',
  'rvben.rumdl',
  'sidneys1.gitconfig',
  'steditor.line-endings',
  'stkb.rewrap',
  'tamasfe.even-better-toml',
  'task.vscode-task',
  'timonwong.shellcheck',
  'tomoki1207.pdf',
  'tyriar.sort-lines',
  'usernamehw.errorlens',
  'wmaurer.change-case',
  'xshrim.txt-syntax',
  'yzhang.markdown-all-in-one',
  'zardoy.fix-all-json',
  # @config-manager:end standard
]
