#!/usr/bin/env bash
set -e

# see also ".mailmap" for how email addresses and names are deduplicated
OUT="${1:-.}"
{
    # editorconfig-checker-disable
    cat <<- 'EOF'
	# File @generated by scripts/generate-contributors.sh. DO NOT EDIT.
	# This file lists all contributors to the repository.
	# See scripts/generate-contributors.sh to make modifications.
	EOF
    # editorconfig-checker-enable

    echo

    # shellcheck disable=2312
    git log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf

} > "${OUT}/CONTRIBUTORS"
cat "${OUT}/CONTRIBUTORS"
