---
# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: Supply-Chain Security
on:
  # For Branch-Protection check. Only the default branch is supported. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
  branch_protection_rule:
  # To guarantee Maintained check is occasionally updated. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#maintained
  schedule:
    - cron: 40 8 * * 5
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  analysis:
    name: Perform analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      # Needed to publish results and get a badge (see publish_results below).
      id-token: write
      # Uncomment the permissions below if installing in a private repository.
      # contents: read
      # actions: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            100.20.106.61:443
            100.23.207.142:443
            100.23.248.170:443
            140.82.112.21:443
            140.82.112.22:443
            140.82.113.24:443
            168.63.129.16:53
            184.33.59.158:443
            185.125.188.54:443
            185.125.188.57:443
            185.125.188.58:443
            185.125.188.59:443
            20.60.6.228:443
            20.60.6.68:443
            20.75.202.224:443
            34.215.80.232:443
            35.155.79.20:443
            35.161.41.177:443
            35.164.214.20:443
            35.165.82.99:443
            35.82.158.68:443
            35.83.36.100:443
            44.225.180.214:443
            44.230.93.154:443
            44.231.40.74:443
            44.236.18.214:443
            44.236.209.64:443
            52.12.202.161:443
            52.13.150.152:443
            52.239.171.36:443
            52.32.169.232:443
            52.40.238.29:443
            52.89.44.252:443
            54.203.170.113:443
            54.203.187.250:443
            54.213.222.183:443
            api.cloudflare.com:443
            api.deps.dev:443
            api.github.com:443
            api.gumroad.com:443
            api.ipify.org:443
            api.osv.dev:443
            api.ote-godaddy.com:443
            api.scorecard.dev:443
            api.securityscorecards.dev:443
            auth.docker.io:443
            bestpractices.coreinfrastructure.org:443
            cdn.fwupd.org:443
            checkpoint-api.hashicorp.com:443
            data.iana.org:443
            definitionupdates.microsoft.com:443
            dl-cdn.alpinelinux.org:443
            ec2.us-east-2.amazonaws.com:443
            example.com:1234
            example.com:443
            example.com:5430
            example.com:5432
            files.pythonhosted.org:443
            fulcio.sigstore.dev:443
            get.opentofu.org:443
            get.trivy.dev:443
            ghcr.io:443
            github-cloud.githubusercontent.com:443
            github-cloud.s3.amazonaws.com:443
            github.com:443
            gitlab.com:443
            global.endpoint.security.microsoft.com:443
            go.dev:443
            go.googlesource.com:443
            go.microsoft.com:443
            golang.org:443
            golangci-lint.run:443
            goreleaser.com:443
            hosted-compute-watchdog-prod-eus-01.githubapp.com:443
            hosted-compute-watchdog-prod-eus-02.githubapp.com:443
            hosted-compute-watchdog-prod-iad-01.githubapp.com:443
            hosted-compute-watchdog-prod-iad-02.githubapp.com:443
            index.crates.io:443
            index.docker.io:443
            lfs.github.com:443
            nodejs.org:443
            oauth2.sigstore.dev:443
            objects.githubusercontent.com:443
            oss-fuzz-build-logs.storage.googleapis.com:443
            osv-vulnerabilities.storage.googleapis.com:443
            pkg-containers.githubusercontent.com:443
            production.cloudflare.docker.com:443
            proxy.golang.org:443
            raw.githubusercontent.com:443
            registry-1.docker.io:443
            registry.npmjs.org:443
            registry.opentofu.org:443
            registry.terraform.io:443
            rekor.sigstore.dev:443
            release-assets.githubusercontent.com:443
            releases.astral.sh:443
            releases.hashicorp.com:443
            sigstore-tuf-root.storage.googleapis.com:443
            snyk.io:443
            static.crates.io:443
            storage.googleapis.com:443
            sts.us-east-2.amazonaws.com:443
            sum.golang.org:443
            tuf-repo-cdn.sigstore.dev:443
            unitedstates.cp.wd.microsoft.com:443
            uploads.github.com:443
            us-v20.events.data.microsoft.com:443
            vuln.go.dev:443
            wdcp.microsoft.com:443
            winatp-gw-cus.microsoft.com:443
            www.bestpractices.dev:443
            x.cp.wd.microsoft.com:443

      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      # Upload the results as artifacts (optional). Commenting out will disable uploads of run results in SARIF
      # format to the repository Actions tab.
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      # Upload the results to GitHub's code scanning dashboard.
      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@7188fc363630916deb702c7fdcf4e481b751f97a # v4.37.1
        with:
          sarif_file: results.sarif
