[formatting]
align_comments        = false
align_entries         = false
allowed_blank_lines   = 1
array_auto_collapse   = true
array_auto_expand     = true
array_trailing_comma  = true
column_width          = 120
compact_arrays        = false
compact_entries       = false
compact_inline_tables = false
crlf                  = false
indent_entries        = true
indent_string         = "  "
indent_tables         = true
inline_table_expand   = false
reorder_arrays        = false
reorder_inline_tables = false
reorder_keys          = false
trailing_newline      = true
